# Generated by Django 4.2.3 on 2024-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='langue',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
