# Generated by Django 4.2.3 on 2024-06-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_sender', to='back.player')),
                ('id_player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_receiver', to='back.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('id_player1', 'id_player2'), name='unique_friendship'),
        ),
    ]
