# Generated by Django 4.2.3 on 2024-06-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='play',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='unique_player_game'),
        ),
    ]
