# Generated by Django 4.2.3 on 2024-06-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_remove_play_game_remove_play_player_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
