version: '4.3.0'

services:
  web:
    container_name: backend
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./.utils/.env
    depends_on:
      - db
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./project
          target: /usr/src/project
          # ignore:
          #   - node_modules/
        # - action: rebuild
        #   path: ./proxy/nginx.conf
        #   target: /etc/nginx/conf.d/default.conf
    links:
      - db:db
    networks:
      - transcendance
      - devops

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ccouliba
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db1
      - POSTGRES_PORT='5432'
    restart: always
    networks:
     - transcendance

  # Elasticsearch is a search engine
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node #for development mode
      - xpack.security.enabled=false #for anonymous request
      # - xpack.monitoring.enabled=true
    ports: #several ports
      - 127.0.0.1:9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - transcendance

  # Logstash is a server-side data processing pipeline
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.14.3
    build: ./project/logstash
    # command: bin/logstash -f /usr/share/logstash/pipeline/logstash.conf --config.test_and_exit --log.level trace #-f ./project/logstash/pipeline/logstash_2.conf
    volumes:
      - ./project/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./project/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # - ./project/logstash/:/usr/share/logstash/
    ports:
      - "5959:5959/tcp"
      - "5959:5959/udp"
    depends_on:
      - elasticsearch
    networks:
      - transcendance

  # Kibana is used for data visualization
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.14.3
    environment:
      - XPACK_SECURITY_ENABLED=false
    # volumes:
    #   - kibana-data:/usr/share/kibana/data
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - transcendance
      - devops

volumes:
  postgres_data:
  es-data:

  # Created another network for devops_front
networks:
  transcendance:
    name: transcendance
    driver: bridge
  devops:
    name: devops
    driver: bridge