# These are not needed in the dockerfile context

# - pipeline.id: pipeline_1
#   path.config: "../pipelines/logstash.conf"
#   pipeline.workers: 2

# - pipeline.id: pipeline_2
#   path.config: "../pipelines/logstash_2.conf"
#   pipeline.workers: 3