# Generated by Django 4.2.3 on 2024-07-27 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
        migrations.DeleteModel(
            name='TournamentParticipant',
        ),
    ]
