# Generated by Django 4.2.3 on 2024-07-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_tournamentparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
