# Generated by Django 4.2.3 on 2024-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
