# Generated by Django 4.2.3 on 2024-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_tournament_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
