# Generated by Django 4.2.3 on 2024-07-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_friendship_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='created_at',
        ),
    ]
