# Generated by Django 4.2.3 on 2024-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0014_user_last_activity_user_losses_user_wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
