# Generated by Django 4.2.3 on 2024-07-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0015_game_finished_at'),
    ]

    operations = [
    ]
