version: '3.8'

services:
  web:
    container_name: backend
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: unless-stopped
    links:
      - db:db
    networks:
      - transcendance

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:8000
      #  - 5433:5432
    environment:
      - POSTGRES_USER=ccouliba
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db1
      - POSTGRES_PORT='5432'
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    networks:
     - transcendance

  # on localhost
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     #- 5432:8000
  #      - 5433:5432
  #   environment:
  #     - POSTGRES_USER=ccouliba
  #    # - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=db1
  #     - POSTGRES_PORT='5432'
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   restart: always
  #   #networks:
  #   #  - transcendance

volumes:
  postgres_data:

networks:
  transcendance:
    name: transcendance
    driver: bridge
