# Logstash config
http.host: "0.0.0.0"

# Chemin vers le dossier des pipelines
path.config: /usr/share/logstash/pipeline

config.reload.automatic: true

allow_superuser: true

# xpack.monitoring.elasticsearch.api_key: "${ELASTIC_API_KEY}"

# xpack.monitoring.elasticsearch.ssl.certificate: /usr/share/logstash/config/certs/ssl.crt

# xpack.monitoring.elasticsearch.ssl.key: /usr/share/logstash/config/certs/ssl.key
