
services:
  web:
    container_name: backend
    build: ./project
    # command: python manage.py runserver 0.0.0.0:8000
    # New command to make it work
    # command: gunicorn server.wsgi:application --bind 0.0.0.0:8000 --certfile=./selfsigned.crt --keyfile=./selfsigned.key

    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8443:8443
    env_file:
      - ./.utils/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    links:
      - db
    networks:
      - transcendance

  db:
    image: postgres:15
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ccouliba
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db1
      - POSTGRES_PORT='5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ccouliba -d db1'"]
      interval: 10s
      timeout: 4s
      retries: 3  
    networks:
     - transcendance
  
  # Elasticsearch is a search engine
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elk_data:/usr/share/elasticsearch/data
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 2
    networks:
      - elk

  # # Logstash is a server-side data processing pipeline
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.14.3
    user: root
    volumes:
      - ./elk_data/logstash/pipeline/:/usr/share/logstash/pipeline/:ro
      - ./project/logs:/logs/
    
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - elk
      - transcendance

  # # Kibana is used for data visualization
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.14.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
    

  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "5555:80"
    networks:
      - elk
    depends_on: 
      - kibana

volumes:
  postgres_data:
  elk_data:
    driver: local
  logs:

networks:
  transcendance:
    name: transcendance
    driver: bridge
  elk:
    name: elk
    driver: bridge