# Generated by Django 4.2.3 on 2024-06-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_of_turn', models.IntegerField()),
                ('alias', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Composed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.game')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.tournament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participate',
            constraint=models.UniqueConstraint(fields=('player', 'tournament'), name='unique_player_tournament'),
        ),
        migrations.AddConstraint(
            model_name='composed',
            constraint=models.UniqueConstraint(fields=('tournament', 'game'), name='unique_game_tournament'),
        ),
    ]
